services:
  client-app-prod:
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
        - VITE_APP_NAME=Finance App
        - VITE_API_URL=https://finance-api.umarsyariif.site
        - VITE_BASE_URL=/
    container_name: finance-client-prod
    ports:
      - '3000:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`finance.umarsyariif.site`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    profiles:
      - prod

  client-app-dev:
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
        - VITE_APP_NAME=Finance App
        - VITE_API_URL=http://localhost:8000
        - VITE_BASE_URL=/
    container_name: finance-client-dev
    ports:
      - '3001:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.rule=Host(`finance-dev.umarsyariif.site`)"
      - "traefik.http.routers.frontend-dev.entrypoints=websecure"
      - "traefik.http.routers.frontend-dev.tls.certresolver=letsencrypt"
    profiles:
      - dev

networks:
  default:
    name: finance-app-network
    external: true