version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance-app
    ports:
      - '6500:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data

  app:
    build:
      context: .
    container_name: backend-app
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: node dist/app.js
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`finance-api.umarsyariif.site`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"

volumes:
  postgresDB:
  redisDB: